model:
  name: 'asnet'
  pretrained: True

data:
  type: 'image'
  sources: ['cuhk03_labeled']
  targets: ['cuhk03_labeled']
  height: 384
  width: 128
  combineall: False
  transforms: ['random_flip']
  save_dir: 'log'
  exp_name: 'cuhk_labeled'

sampler:
  train_sampler: 'RandomIdentitySampler'
  num_instances: 4

loss:
  name: 'engine_as_net'
  softmax:
    label_smooth: True
  triplet:
    weight_t: 1.
    weight_x: 1.

train:
  optim: 'adam'
  lr: 0.000025
  max_epoch: 130
  batch_size: 64
  lr_scheduler: 'warmup'
  warmup_multiplier: 18
  gamma: 0.2
  stepsize: [30, 60, 90]


test:
  batch_size: 100
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 1
  start_eval: 60
  rerank: False
  visactmap: False
